apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: std-1
  namespace: openshift-gitops
  labels:
    gitops.tier.layer: infra
spec:
  description: The ArgoCD project to manage the real time inventory Solution deployment
  sourceRepos: 
  - https://github.ibm.com/boyerje/eda-tech-academy.git
  # Only permit applications to deploy to the following namespace in the same cluster
  destinations:
  - namespace: std-1
    server: https://kubernetes.default.svc
  - namespace: cp4i-eventstreams
    server: https://kubernetes.default.svc
  - namespace: openshift-gitops
    server: https://kubernetes.default.svc
  - namespace: openshift-operators
    server: https://kubernetes.default.svc
  clusterResourceWhitelist:
  - group: "*"
    kind: "*"
  roles:
  # A role which provides read-only access to all applications in the project
  - name: read-only
    description: Read-only privileges to this project
    policies:
    - p, proj:std-1:read-only, applications, get, std-1/*, allow
    groups:
    - argocd-admins