apiVersion: mq.ibm.com/v1beta1
kind: QueueManager
metadata:
  name: qmgr1
  namespace: std-1
spec:
  license:
    accept: true
    license: L-RJON-C7QG3S
    use: NonProduction
  queueManager:
    name: MQGR1
    mqsc:
      - configMap:
          name: mq-mqsc-config
          items:
            -  example.mqsc
    resources:
      limits:
        cpu: 250m
        memory: 1Gi
      requests:
        cpu: 250m
        memory: 1Gi
    metrics:
      enabled: true
    route:
      enabled: true
    readinessProbe:
      failureThreshold: 1
      initialDelaySeconds: 10
      periodSeconds: 5
      successThreshold: 1
      timeoutSeconds: 3
    livenessProbe:
      failureThreshold: 1
      initialDelaySeconds: 90
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 5
    imagePullPolicy: IfNotPresent
    debug: false
    logFormat: Basic
    availability:
      type: SingleInstance
      updateStrategy: RollingUpdate
    storage:
      defaultClass: ocs-storagecluster-ceph-rbd
      persistedData:
        enabled: false
      queueManager:
        size: 2Gi
        type: persistent-claim
      recoveryLogs:
        enabled: false
  securityContext:
    initVolumeAsRoot: false
  template:
    pod:
      containers:
        - name: qmgr
          env:
            - name: MQSNOAUT
              value: 'yes' 

  version: 9.2.4.0-r1
  web:
    enabled: true

