apiVersion: v1
kind: ServiceAccount
metadata:
  name: rt-inv-job-sa
  namespace: cody1
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: secrets-to-sa
subjects:
  - kind: ServiceAccount
    name: rt-inv-job-sa
    namespace: cody1
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin