apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app.kubernetes.io/name: store-simulator
    app.kubernetes.io/version: 0.0.10
  name: store-simulator
spec:
  host: ""
  path: /
  port:
    targetPort: http
  to:
    kind: Service
    name: store-simulator

