apiVersion: batch/v1
kind: Job
metadata:
  name: cp-tls-usr-secret
  namespace: ahsoka20
spec:
  template:
    metadata:
      name: cp-tls-usr-secret
    spec:
      containers:
      - command:
        - bin/bash
        - -c
        - "if [ -z \"$(kubectl get secret ahsoka20-tls-user -n ahsoka20 | grep found)\" ]; \
          then kubectl get secret ahsoka20-tls-user -n cp4i-eventstreams -o json \
          | jq -r '.metadata.namespace=\"ahsoka20\"' \
          | jq  'del(.metadata.uid, .metadata.selfLink, .metadata.ownerReferences,  .metadata.resourceVersion, .metadata.creationTimestamp)'  \
          | kubectl apply -n ahsoka20 -f - ;\
          else echo already_created; fi"
        image: bitnami/kubectl
        name: copysecret
      restartPolicy: Never
      serviceAccountName: rt-inv-job-sa
